### PR TITLE
Added some layers of hacks

### PR DESCRIPTION
**Pull request by edgarsi**
If something doesn't work, let me know, I'll look into better usage descriptions and/or portability.

### CODE REVIEW

**Comment by pjf** [comment]
Oh gosh, you are amazing! I've been camping in Western Australia and have been running through all my notifications, and this is great! I've checked this out and am playing with it now, but may not have a chance to merge until after lunch.

Thank you again! You _totally_ rock. :)

**Comment by pjf** [comment]
Double wow. Everything here is amazing. And I've realised I've totally not put a license on my code. Are you happy with something like code is GPLv2, and output remains that of the anki authors and contributors?

**Comment by pjf** [comment]
Also merging, because this is better than what we had before in every possible way. Thank you!

**Comment by edgarsi** [comment]
Thanks for the accolades :D But I don't intend to continue with this project. Some hacking every once in a while is fun but it is not obvious where this project could go further and still be more fun than effort.

Licensing is intended for those who want money, recognition, or protection against evil abuse. For this project... I'd leave it without a license. But please do whatever you feel is right or like doing! I'm putting no restrictions.

**Pull request merged**
